### PR TITLE
Use correct include path, should fix #415

### LINKED ISSUE #415: Using ospray_testing needs extra include directory
Even though the ospray_testing headers are included in the superbuild using only -I <ospray>/include` isn't enough, as one of the headers is then not found due to an incorrect quoted reference in `ospray/ospray_testing/builders/Builder.h`:

```
melis@juggle 19:15:~/concepts/blender-ospray-engine$ cat t.cc
#include <ospray/ospray.h>
#include <ospray/ospray_testing/ospray_testing.h>

melis@juggle 19:15:~/concepts/blender-ospray-engine$ g++ -c -I ~/software/ospray-superbuild-git/include/ t.cc
In file included from /home/melis/software/ospray-superbuild-git/include/ospray/ospray_testing/detail/ospray_testing.inl:4,
                 from /home/melis/software/ospray-superbuild-git/include/ospray/ospray_testing/ospray_testing.h:39,
                 from t.cc:2:
/home/melis/software/ospray-superbuild-git/include/ospray/ospray_testing/detail/../builders/Builder.h:12:10: fatal error: ospray_testing_export.h: No such file or directory
   12 | #include "ospray_testing_export.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### PR DESCRIPTION
**Pull request by paulmelis**

### CODE REVIEW

**Comment by johguenther** [comment]
Unfortunately this is not robust enough as is breaks the "normal" build. Looking for alternatives.

**Comment by paulmelis** [comment]
Strange that the build fails, as I rebuilt locally after the change to check. But maybe that's because I rebuilt as part of the superbuild

**Comment by johguenther** [comment]
I found the superbuild tricky to test changes: even with `ALWAYS_REBUILD=ON` a rebuild is not triggered reliably. The only way to be really sure is to nuke the whole build folder.

**Comment by paulmelis** [comment]
Right, I indeed clean it out when needed with extra time used for that. I guess I could install ccache as some sort of a workaround, as I feel the non-superbuild is a bit tricky to do in keeping all dependencies correct in terms of versions.

**Comment by johguenther** [comment]
I think the proper fix is for the app is to link against target `ospray::ospray_testing`, see https://github.com/RenderKit/ospray/issues/415#issuecomment-2239177246.

**Pull request closed without merging**
